services:
  # Start Home Assistant with Docker.
  # This config is alternative from command from https://www.home-assistant.io/installation/linux/#platform-installation:
  # docker run -d \
  #   --name homeassistant \
  #   --privileged \
  #   --restart=unless-stopped \
  #   -e TZ=MY_TIME_ZONE \
  #   -v /PATH_TO_YOUR_CONFIG:/config \
  #   -v /run/dbus:/run/dbus:ro \
  #   --network=host \
  #   ghcr.io/home-assistant/home-assistant:stable
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    privileged: true
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./home-assistant/config:/config
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123