version: '3'
services:

  # Home Assistant config, see: https://www.home-assistant.io/installation/linux/#platform-installation
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    privileged: true
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./home-assistant/config:/config
      - /run/dbus:/run/dbus:ro
    ports:
      - '127.0.0.1:8123:8123'
    depends_on:
      - nginx

  # NGINX
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
