services:
  # Home Assistant config, see: https://www.home-assistant.io/installation/linux/#platform-installation
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    privileged: true
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./home-assistant/config:/config
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123