services:

  # Home Assistant config, see: https://www.home-assistant.io/installation/linux/#platform-installation
  homeassistant:
    build: ./home-assistant.dockerfile
    container_name: home-assistant
    privileged: true
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./home-assistant/config:/config
      - /run/dbus:/run/dbus:ro
    ports:
      - '127.0.0.1:8123:8123'

  # NGINX
  nginx:
    image: nginx:1.26.0-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
